### PR TITLE
added length-specified (in addition to null-terminated) serial put

### PR DESCRIPTION
**Pull request by Phildo**
I know wiringpi.com currently appears to be keeping its distance from github forks, but its git repository is also down and am not sure how else to contribute. I needed this function for a project of mine, and can't see any reason it isn't already included (except that "wiringSerial" is likely a little-used module which doesn't get a lot of attention). Let me know if there are better means of contributing to this project in a more permanent way, and also please let me know if there are disagreements about the function name/signature/etc...

### CODE REVIEW

**Comment by liffiton** [comment]
This repository is sort of in limbo right now.  I think I might be the only active maintainer at the moment, but I only really signed on to help maintain the Python library.  I'm just making minimal changes to this repository to keep the Python library working on newer RPi versions.  I am not the right person to shepherd further development of the code or process pull requests.  At some point, someone should probably fork the project cleanly.

Right now, though, I see pull requests here as a decent way for others to contribute.  Even if they aren't merged (and at least *I* don't plan to merge them), they can serve to direct people toward variants or updates of the code that solve certain problems.

**Comment by bramburn** [comment]
the main repo is kinda dead
i'm working on the main wiringPI at the moment for c++. I will be publishing it onto vcpkg soon once i get the cross compiler to work.

**Comment by JakeSays** [comment]
@liffiton Hey if you are looking for someone to help on the C/C++ side, I'd like to volunteer.

**Comment by bramburn** [comment]
@JakeSays I think they're not going to PR into the main repo.
Thinking of running a separate Repo for things going forward.

**Comment by liffiton** [comment]
@JakeSays, thank you for the offer.  I'm not an owner of this organization, so I can't add people myself.  Gadgetoid and Eugene Ware (listed [here](https://github.com/orgs/WiringPi/people)) are the owners who might be able to add someone.

I'll make another issue and pin it for others to more easily learn the status of this repository and discuss it if they want.  (Sorry to clutter your issue with this tangential discussion, @Phildo.)

**Pull request closed without merging**
