### PR TITLE
Remove projects@drogon.net contact from build

### PR DESCRIPTION
**Pull request by Gadgetoid**
In an effort to avoid any unecessary contact with Gordon, I've updated the build output error instructions to direct users to raise an issue.

### CODE REVIEW

**Review by liffiton — COMMENTED** [review]
Good call.  I think we can also remove the email from other places where it might lead to unwanted messages:
  * INSTALL
  * gpio/gpio.1
  * newVersion

And maybe just remove the commented block starting on line 113 of build, though that's not critical.

**Comment by Gadgetoid** [comment]
> And maybe just remove the commented block starting on line 113 of build, though that's not critical

Haha, I had a huge "wat" moment when I came across that. I had just compiled on a non-Pi and thought "surely.. I'd have seen this?" Then saw it was commented out 🤦 

I'll take a look at those other instances. Thank you!

**Comment by Gadgetoid** [comment]
Not sure what to do about `newVersion` - if we're moving forward to shipping a new unofficial life-support release of wiringPi then we'd probably need to change that, but I'm hesitant at the moment.

**Review by liffiton — APPROVED** [review]
Looks good!

**Pull request merged**
