### PR TITLE
Add support for the Zero 2 W

### PR DESCRIPTION
**Pull request by PinkFreud**

### CODE REVIEW

**Comment by amcelroy** [comment]
This is still showing 2.6 when running gpio -v:
gpio version: 2.60
Copyright (c) 2012-2018 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty

Raspberry Pi Details:
  Type: Unknown18, Revision: 00, Memory: 512MB, Maker: Sony
  * Device tree is enabled.
  *--> Raspberry Pi Zero 2 Rev 1.0
  * This Raspberry Pi supports user-level GPIO access.


Confirmed compiling and it prints the GPIO table. Need to test with O-Scope to validate a handful of pins to ensure functionality. Looking good so far!

**Comment by PinkFreud** [comment]
> This is still showing 2.60 when running gpio -v:

Fixed!  Damn, it's somewhat ridiculous how many places the version number needs to be changed in.  ;)  I've also fixed the Unknown18 designation by adding the Zero 2 W to piModelNames in wiringPi/wiringPi.c.

$ gpio -v
gpio version: 2.61
Copyright (c) 2012-2018 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty

Raspberry Pi Details:
  Type: Pi Zero2-W, Revision: 00, Memory: 512MB, Maker: Sony 
  * Device tree is enabled.
  *--> Raspberry Pi Zero 2 Rev 1.0
  * This Raspberry Pi supports user-level GPIO access.

**Comment by Melanooma** [comment]
Tested these changes and seems to work, I was able to read the GPIO's on my RPI Zero2W with this !

**Review by fleek — APPROVED** [review]

**Review by liffiton — APPROVED** [review]
Everything looks good to me.

**Comment by liffiton** [comment]
Thanks for the contributions, everyone!

**Pull request merged**
