### PR TITLE
cmake: make it support build with cmake

### PR DESCRIPTION
**Pull request by sndnvaps**
use cmake . , to gen the Makefile
1. support cmake to gen the Makefile
2. support build deb package
3. remove all the makefile

Signed-off-by: sndnvaps sndnvaps@gmail.com

### CODE REVIEW

**Comment by bramburn** [comment]
i have modified the code to include cmake and vcpkg. I will publish as soon as I can clean up and remove all the redudant makefile + test it on my raspberrypi. I am building it via a debian WSL

**Comment by wenwenchenbosch** [comment]
is there any plan to merge this pr? it would be very helpful

**Comment by sndnvaps** [comment]
> is there any plan to merge this pr? it would be very helpful

i don't know. but i just resolve the confict..

**Comment by 2bndy5** [comment]
This PR is exactly what I came here looking for! Although, there are some things I'd still like to contribute:

1. Removing the old makefiles isn't backwards compatible; merging this as is would require a bump in Major version. Keeping the Makefiles would be better as long as CMake is ensured that it is doing an out-of-source build env (easily done with an `if` cmd).
2. I think that the debian package policy follows a different naming convention than what CPack uses by default.
3. I have put together a generic toolchain file to cross-compile CMake projects with the arm-gnueabihf compiler.

**Pull request closed without merging**
