### PR TITLE
add CMake

### PR DESCRIPTION
**Pull request by bernardoaraujor**
You can use CMake to cross compile WiringPi. This is heavily inspired by Alex C. U.'s article [The Useful RaspberryPi Cross Compile Guide](https://medium.com/@au42/the-useful-raspberrypi-cross-compile-guide-ea56054de187).

The main difference is that it assumes you are using [Embedded Development Infrastructure (edi)](https://docs.get-edi.io/en/latest/introduction.html). For more info, follow Matthias Lüscher’s [Cross Compiling for Raspbian Buster](https://www.get-edi.io/Cross-Compiling-for-Raspbian-Buster/) guide to set up an edi container.

### CODE REVIEW

**Comment by bernardoaraujor** [comment]
just realized there's more work to be done.
I'll reopen when it's ready, sorry.

**Comment by bramburn** [comment]
hey buddy already added and built but they won't PR into wiringPI as its used as an archive.

**Comment by bramburn** [comment]
here is the complete build but im using it for VCPKG
https://github.com/bramburn/wiringpi/

cmake works and outputs to out/llib out/include instead of usr/local/lib .

**Comment by bramburn** [comment]
@bernardoaraujor  if you want to work together we can improve the extensions on the library and write a guide.

**Comment by bernardoaraujor** [comment]
sounds good @bramburn ! I'd love to collaborate.
your version does a few things mine is missing, namely the gpio executable.

I started writing this so I can install wiringPi into a cross compile environment's sysroot, so in that regard the output directories cannot be the ones set in your repo.

**Comment by bramburn** [comment]
i could cross compile using vcpkg. The only problem I had is that the latest version of VCPKG messed up my ports. I was cross compiling on my debian WSL for my rasberry pi.

**Pull request closed without merging**
