### PR TITLE
build: Create DESTDIR subdirectories before installing

### PR DESCRIPTION
**Pull request by rzr**
Change-Id: I4157f26ad9c828da6f552a360fdce1f7d030d4f3
Origin: https://github.com/tizenteam/WiringPi
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

### CODE REVIEW

**Comment by rzr** [comment]
I guess this PR is still valid please review @liffiton

**Comment by liffiton** [comment]
From the README: "Pull-requests are not currently accepted, since this is a mirror."

Leaving issues and pull requests open has some value for pointing others toward fixes or workarounds they might wish to use, but this repository is not going to merge them.

**Comment by rzr** [comment]
Ok sorry for noise, I have forwarded the patch by email anyway:

https://github.com/WiringPi/WiringPi/pull/49/commits/62a256c8f98ef864a2ebd1be1772379a128bd530.patch

**Comment by rzr** [comment]
Still not merged, comments welcome if you think it should be revised.

**Comment by rzr** [comment]
Is there any fork which can be considered as alternative place to contribute ?

**Comment by liffiton** [comment]
I don't know of any well-known forks.  There are all of the Github forks [here](https://github.com/WiringPi/WiringPi/network), but I'm not sure any of those are intended to be full-on forks of the project.

**Pull request closed without merging**
